site_name: Auditor Cidadão - Documentação Técnica
theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md